-- Spectrum: Monokai Pro Filter Spectrum V2 for Neovim 0.12+.
-- Core groups first; Treesitter / LSP fall back to them. Float interiors,
-- borders, and markdown code spans share one background so rounded
-- winborder cells don't paint outside the glyph.

local M = {}

local function apply(groups)
	for name, spec in pairs(groups) do
		if spec.link then
			spec.force = true
		end
		vim.api.nvim_set_hl(0, name, spec)
	end
end

function M.load()
	vim.o.background = "dark"
	vim.cmd.highlight("clear")
	vim.g.colors_name = "spectrum"
	vim.o.termguicolors = true

	local p = require("spectrum.palette")
	local float = { fg = p.fg, bg = p.bg }

	-- Editor ----------------------------------------------------------------
	apply({
		Normal = { fg = p.fg, bg = p.bg },
		NormalNC = { fg = p.fg, bg = p.bg },
		NormalFloat = float,
		FloatBorder = { fg = p.fg_muted, bg = p.bg },
		FloatTitle = { fg = p.yellow, bg = p.bg, bold = true },
		FloatFooter = { fg = p.fg_muted, bg = p.bg },
		FloatShadow = { bg = p.bg_darker, blend = 80 },
		FloatShadowThrough = { bg = p.bg_darker, blend = 100 },

		ColorColumn = { bg = p.bg_element },
		Conceal = { fg = p.fg_dim },
		Cursor = { fg = p.bg, bg = p.fg },
		lCursor = { fg = p.bg, bg = p.fg },
		CursorIM = { fg = p.bg, bg = p.fg },
		TermCursor = { fg = p.bg, bg = p.fg },
		CursorLine = { bg = p.bg_cursor },
		CursorColumn = { bg = p.bg_cursor },
		CursorLineNr = { fg = p.fg, bold = true },
		LineNr = { fg = p.fg_dark },
		LineNrAbove = { link = "LineNr" },
		LineNrBelow = { link = "LineNr" },
		SignColumn = { fg = p.fg_dark, bg = p.bg },
		FoldColumn = { fg = p.fg_soft, bg = p.bg },
		Folded = { fg = p.fg_muted, bg = p.bg_dark },
		CursorLineFold = { link = "FoldColumn" },
		CursorLineSign = { link = "SignColumn" },
		EndOfBuffer = { fg = p.bg },
		NonText = { fg = p.fg_dark },
		SpecialKey = { fg = p.fg_dark },
		Whitespace = { fg = p.fg_dark },
		WinSeparator = { fg = p.bg_border, bg = p.bg },
		VertSplit = { link = "WinSeparator" },
		WinBar = { fg = p.fg, bg = p.bg, bold = true },
		WinBarNC = { fg = p.fg_muted, bg = p.bg },

		StatusLine = { fg = p.fg, bg = p.bg_dark },
		StatusLineNC = { fg = p.fg_muted, bg = p.bg_dark },
		StatusLineTerm = { link = "StatusLine" },
		StatusLineTermNC = { link = "StatusLineNC" },
		TabLine = { fg = p.fg_muted, bg = p.bg_dark },
		TabLineFill = { bg = p.bg_dark },
		TabLineSel = { fg = p.fg, bg = p.bg, bold = true },
		Title = { fg = p.yellow, bold = true },
		Directory = { fg = p.cyan },
		Question = { fg = p.yellow },
		MoreMsg = { fg = p.yellow },
		ModeMsg = { fg = p.fg, bold = true },
		MsgArea = { fg = p.fg, bg = p.bg },
		MsgSeparator = { fg = p.bg_border, bg = p.bg },
		ErrorMsg = { fg = p.pink },
		WarningMsg = { fg = p.orange },
		OkMsg = { fg = p.green },
		StderrMsg = { fg = p.pink },
		StdoutMsg = { fg = p.fg },
		WildMenu = { fg = p.bg, bg = p.yellow, bold = true },
		QuickFixLine = { bg = p.bg_cursor, bold = true },

		Visual = { bg = p.bg_visual },
		VisualNOS = { link = "Visual" },
		Search = { bg = p.bg_search },
		IncSearch = { fg = p.bg, bg = p.yellow, bold = true },
		CurSearch = { fg = p.bg, bg = p.yellow, bold = true },
		Substitute = { fg = p.bg, bg = p.pink, bold = true },
		MatchParen = { fg = p.yellow, bold = true, underline = true },

		-- PmenuSel / PmenuMatch cascade onto Pmenu in 0.11+: only set the delta.
		Pmenu = float,
		PmenuSel = { bg = p.bg_cursor, bold = true },
		PmenuKind = { fg = p.cyan },
		PmenuKindSel = { fg = p.cyan },
		PmenuExtra = { fg = p.fg_muted },
		PmenuExtraSel = { fg = p.fg_muted },
		PmenuSbar = { bg = p.bg_element },
		PmenuThumb = { bg = p.fg_dark },
		PmenuBorder = { fg = p.fg_muted, bg = p.bg },
		PmenuMatch = { fg = p.orange, bold = true },
		PmenuMatchSel = { fg = p.orange, bold = true },
		PmenuShadow = { bg = p.bg_darker, blend = 80 },
		PmenuShadowThrough = { bg = p.bg_darker, blend = 100 },
		ComplMatchIns = { fg = p.fg_dim },
		PreInsert = { fg = p.green, italic = true },
		ComplHint = { fg = p.fg_dim, italic = true },
		ComplHintMore = { fg = p.cyan },
		SnippetTabstop = { bg = p.bg_search },
		SnippetTabstopActive = { bg = p.bg_visual, bold = true },
	})

	-- Syntax ----------------------------------------------------------------
	apply({
		Comment = { fg = p.fg_dim, italic = true },
		Constant = { fg = p.purple },
		String = { fg = p.yellow },
		Character = { fg = p.yellow },
		Number = { fg = p.purple },
		Boolean = { fg = p.purple },
		Float = { fg = p.purple },
		Identifier = { fg = p.fg },
		Function = { fg = p.green },
		Statement = { fg = p.pink },
		Conditional = { fg = p.pink },
		Repeat = { fg = p.pink },
		Label = { fg = p.purple },
		Operator = { fg = p.pink },
		Keyword = { fg = p.pink },
		Exception = { fg = p.pink },
		PreProc = { fg = p.cyan },
		Include = { fg = p.pink },
		Define = { fg = p.pink },
		Macro = { fg = p.cyan },
		PreCondit = { fg = p.cyan },
		Type = { fg = p.cyan, italic = true },
		StorageClass = { fg = p.pink },
		Structure = { fg = p.cyan, italic = true },
		Typedef = { fg = p.cyan, italic = true },
		Special = { fg = p.orange },
		SpecialChar = { fg = p.purple },
		Tag = { fg = p.pink },
		Delimiter = { fg = p.fg_muted },
		SpecialComment = { fg = p.fg_dim },
		Debug = { fg = p.orange },
		Underlined = { underline = true },
		Bold = { bold = true },
		Italic = { italic = true },
		Ignore = { fg = p.fg_dark },
		Error = { fg = p.pink },
		Todo = { fg = p.purple, bold = true },
		Added = { fg = p.green },
		Changed = { fg = p.orange },
		Removed = { fg = p.pink },
	})

	-- Diff / spell ----------------------------------------------------------
	apply({
		DiffAdd = { bg = p.add_bg },
		DiffChange = { bg = p.change_bg },
		DiffDelete = { fg = p.pink, bg = p.delete_bg },
		DiffText = { bg = p.bg_search },
		DiffTextAdd = { bg = p.add_word_bg },
		diffAdded = { link = "Added" },
		diffChanged = { link = "Changed" },
		diffRemoved = { link = "Removed" },
		diffFile = { fg = p.yellow },
		diffNewFile = { fg = p.green },
		diffOldFile = { fg = p.pink },
		diffLine = { fg = p.cyan },
		diffIndexLine = { fg = p.purple },
		SpellBad = { sp = p.pink, undercurl = true },
		SpellCap = { sp = p.orange, undercurl = true },
		SpellLocal = { sp = p.cyan, undercurl = true },
		SpellRare = { sp = p.purple, undercurl = true },
		healthError = { fg = p.pink },
		healthSuccess = { fg = p.green },
		healthWarning = { fg = p.orange },
	})

	-- Diagnostics: floating groups have no bg so they sit on NormalFloat.
	apply({
		DiagnosticError = { fg = p.pink },
		DiagnosticWarn = { fg = p.orange },
		DiagnosticInfo = { fg = p.yellow },
		DiagnosticHint = { fg = p.fg_muted },
		DiagnosticOk = { fg = p.green },
		DiagnosticUnnecessary = { fg = p.fg_dim, italic = true },
		DiagnosticDeprecated = { sp = p.pink, strikethrough = true },
		DiagnosticUnderlineError = { sp = p.pink, undercurl = true },
		DiagnosticUnderlineWarn = { sp = p.orange, undercurl = true },
		DiagnosticUnderlineInfo = { sp = p.yellow, undercurl = true },
		DiagnosticUnderlineHint = { sp = p.fg_muted, undercurl = true },
		DiagnosticUnderlineOk = { sp = p.green, undercurl = true },
		DiagnosticVirtualTextError = { fg = p.pink, bg = p.error_bg },
		DiagnosticVirtualTextWarn = { fg = p.orange, bg = p.warn_bg },
		DiagnosticVirtualTextInfo = { fg = p.yellow, bg = p.info_bg },
		DiagnosticVirtualTextHint = { fg = p.fg_muted, bg = p.hint_bg },
		DiagnosticVirtualTextOk = { fg = p.green, bg = p.add_bg },
		DiagnosticFloatingError = { link = "DiagnosticError" },
		DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
		DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
		DiagnosticFloatingHint = { link = "DiagnosticHint" },
		DiagnosticFloatingOk = { link = "DiagnosticOk" },
		DiagnosticSignError = { link = "DiagnosticError" },
		DiagnosticSignWarn = { link = "DiagnosticWarn" },
		DiagnosticSignInfo = { link = "DiagnosticInfo" },
		DiagnosticSignHint = { link = "DiagnosticHint" },
		DiagnosticSignOk = { link = "DiagnosticOk" },
	})

	-- LSP -------------------------------------------------------------------
	apply({
		LspReferenceText = { bg = p.bg_search },
		LspReferenceRead = { bg = p.bg_search },
		LspReferenceWrite = { bg = p.bg_visual },
		LspReferenceTarget = { bg = p.bg_search },
		LspInlayHint = { fg = p.fg_dim, italic = true },
		LspCodeLens = { fg = p.fg_dim, italic = true },
		LspCodeLensSeparator = { fg = p.fg_dark },
		LspSignatureActiveParameter = { fg = p.orange, bold = true },
		LspInfoBorder = { link = "FloatBorder" },
	})

	-- Treesitter: only where Spectrum differs from the builtin links.
	-- Never set `bg` on markup/raw groups — hover / markdown inherit NormalFloat.
	apply({
		["@comment"] = { link = "Comment" },
		["@comment.documentation"] = { fg = p.fg_dim },
		["@comment.error"] = { fg = p.pink, italic = true },
		["@comment.warning"] = { fg = p.orange, italic = true },
		["@comment.todo"] = { link = "Todo" },
		["@comment.note"] = { fg = p.cyan, italic = true },

		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { link = "Constant" },
		["@constant.macro"] = { link = "Constant" },
		["@boolean"] = { link = "Boolean" },
		["@number"] = { link = "Number" },
		["@number.float"] = { link = "Float" },

		["@string"] = { link = "String" },
		["@string.documentation"] = { link = "Comment" },
		["@string.escape"] = { link = "SpecialChar" },
		["@string.regexp"] = { link = "String" },
		["@string.special"] = { link = "Special" },
		["@string.special.symbol"] = { link = "Special" },
		["@string.special.url"] = { fg = p.green, underline = true },
		["@character"] = { link = "Character" },
		["@character.special"] = { link = "SpecialChar" },

		["@variable"] = { link = "Identifier" },
		["@variable.builtin"] = { fg = p.fg_soft, italic = true },
		["@variable.parameter"] = { fg = p.orange, italic = true },
		["@variable.parameter.builtin"] = { fg = p.orange, italic = true },
		["@variable.member"] = { link = "Identifier" },
		["@property"] = { link = "Identifier" },
		["@field"] = { link = "Identifier" },
		["@attribute"] = { fg = p.cyan, italic = true },
		["@attribute.builtin"] = { fg = p.cyan, italic = true },
		["@label"] = { link = "Label" },
		["@module"] = { fg = p.cyan },
		["@module.builtin"] = { fg = p.cyan },

		["@function"] = { link = "Function" },
		["@function.builtin"] = { link = "Function" },
		["@function.call"] = { link = "Function" },
		["@function.macro"] = { link = "Function" },
		["@function.method"] = { link = "Function" },
		["@function.method.call"] = { link = "Function" },
		["@constructor"] = { link = "Function" },

		["@keyword"] = { link = "Keyword" },
		["@keyword.coroutine"] = { link = "Keyword" },
		["@keyword.function"] = { link = "Keyword" },
		["@keyword.operator"] = { link = "Operator" },
		["@keyword.import"] = { link = "Include" },
		["@keyword.type"] = { link = "Type" },
		["@keyword.modifier"] = { link = "Keyword" },
		["@keyword.repeat"] = { link = "Repeat" },
		["@keyword.return"] = { link = "Keyword" },
		["@keyword.debug"] = { link = "Debug" },
		["@keyword.exception"] = { link = "Exception" },
		["@keyword.conditional"] = { link = "Conditional" },
		["@keyword.conditional.ternary"] = { link = "Operator" },
		["@keyword.directive"] = { link = "PreProc" },
		["@keyword.directive.define"] = { link = "Define" },

		["@operator"] = { link = "Operator" },
		["@punctuation"] = { link = "Delimiter" },
		["@punctuation.delimiter"] = { link = "Delimiter" },
		["@punctuation.bracket"] = { link = "Delimiter" },
		["@punctuation.special"] = { link = "Special" },

		["@type"] = { link = "Type" },
		["@type.builtin"] = { link = "Type" },
		["@type.definition"] = { link = "Type" },
		["@type.qualifier"] = { link = "Keyword" },

		["@tag"] = { link = "Tag" },
		["@tag.attribute"] = { fg = p.cyan, italic = true },
		["@tag.delimiter"] = { link = "Delimiter" },
		["@tag.builtin"] = { link = "Tag" },

		["@diff.plus"] = { link = "Added" },
		["@diff.minus"] = { link = "Removed" },
		["@diff.delta"] = { link = "Changed" },

		["@markup.strong"] = { fg = p.fg, bold = true },
		["@markup.italic"] = { fg = p.fg, italic = true },
		["@markup.strikethrough"] = { fg = p.fg_muted, strikethrough = true },
		["@markup.underline"] = { link = "Underlined" },
		["@markup.heading"] = { link = "Title" },
		["@markup.quote"] = { fg = p.fg_muted, italic = true },
		["@markup.math"] = { fg = p.orange },
		["@markup.link"] = { fg = p.green },
		["@markup.link.label"] = { fg = p.green, italic = true },
		["@markup.link.url"] = { fg = p.green, underline = true },
		["@markup.raw"] = { fg = p.orange },
		["@markup.raw.block"] = { fg = p.orange },
		["@markup.list"] = { fg = p.pink },
		["@markup.list.checked"] = { fg = p.green },
		["@markup.list.unchecked"] = { fg = p.fg_muted },
	})

	for i = 1, 6 do
		apply({
			["@markup.heading." .. i] = { fg = p.yellow, bold = true },
		})
	end

	-- Legacy markdown syntax (no treesitter) + render-markdown.nvim.
	apply({
		markdownH1 = { link = "@markup.heading.1" },
		markdownH2 = { link = "@markup.heading.2" },
		markdownH3 = { link = "@markup.heading.3" },
		markdownH4 = { link = "@markup.heading.4" },
		markdownH5 = { link = "@markup.heading.5" },
		markdownH6 = { link = "@markup.heading.6" },
		markdownHeadingDelimiter = { fg = p.fg_dim },
		markdownBold = { link = "@markup.strong" },
		markdownItalic = { link = "@markup.italic" },
		markdownCode = { fg = p.orange },
		markdownCodeBlock = { fg = p.orange },
		markdownCodeDelimiter = { fg = p.fg_dim },
		markdownUrl = { link = "@markup.link.url" },
		markdownLinkText = { link = "@markup.link" },
		markdownListMarker = { link = "@markup.list" },
		markdownOrderedListMarker = { link = "@markup.list" },
		markdownRule = { fg = p.fg_dim },
		markdownBlockquote = { link = "@markup.quote" },
		htmlH1 = { link = "@markup.heading.1" },
		htmlH2 = { link = "@markup.heading.2" },
		htmlH3 = { link = "@markup.heading.3" },
		htmlBold = { link = "Bold" },
		htmlItalic = { link = "Italic" },
		RenderMarkdownCode = { bg = "NONE" },
		RenderMarkdownCodeInline = { fg = p.orange },
		RenderMarkdownH1 = { link = "@markup.heading.1" },
		RenderMarkdownH2 = { link = "@markup.heading.2" },
		RenderMarkdownH3 = { link = "@markup.heading.3" },
		RenderMarkdownH4 = { link = "@markup.heading.4" },
		RenderMarkdownH5 = { link = "@markup.heading.5" },
		RenderMarkdownH6 = { link = "@markup.heading.6" },
		RenderMarkdownBullet = { link = "@markup.list" },
		RenderMarkdownQuote = { link = "@markup.quote" },
		RenderMarkdownDash = { fg = p.fg_dark },
	})

	-- Semantic tokens -------------------------------------------------------
	apply({
		["@lsp.type.class"] = { link = "Type" },
		["@lsp.type.comment"] = { link = "Comment" },
		["@lsp.type.decorator"] = { link = "Function" },
		["@lsp.type.enum"] = { link = "Constant" },
		["@lsp.type.enumMember"] = { link = "Constant" },
		["@lsp.type.event"] = { link = "Special" },
		["@lsp.type.function"] = { link = "Function" },
		["@lsp.type.interface"] = { link = "Type" },
		["@lsp.type.keyword"] = { link = "Keyword" },
		["@lsp.type.macro"] = { link = "Macro" },
		["@lsp.type.method"] = { link = "Function" },
		["@lsp.type.modifier"] = { link = "Keyword" },
		["@lsp.type.namespace"] = { link = "@module" },
		["@lsp.type.number"] = { link = "Number" },
		["@lsp.type.operator"] = { link = "Operator" },
		["@lsp.type.parameter"] = { link = "@variable.parameter" },
		["@lsp.type.property"] = { link = "@property" },
		["@lsp.type.regexp"] = { link = "@string.regexp" },
		["@lsp.type.string"] = { link = "String" },
		["@lsp.type.struct"] = { link = "Type" },
		["@lsp.type.type"] = { link = "Type" },
		["@lsp.type.typeParameter"] = { link = "Type" },
		["@lsp.type.variable"] = { link = "@variable" },
		["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
		["@lsp.typemod.function.defaultLibrary"] = { link = "Function" },
		["@lsp.mod.deprecated"] = { strikethrough = true },
	})

	-- Terminal ANSI (blue is orange, matching Zed / Ghostty Spectrum)
	vim.g.terminal_color_0 = p.bg_element
	vim.g.terminal_color_1 = p.pink
	vim.g.terminal_color_2 = p.green
	vim.g.terminal_color_3 = p.yellow
	vim.g.terminal_color_4 = p.orange
	vim.g.terminal_color_5 = p.purple
	vim.g.terminal_color_6 = p.cyan
	vim.g.terminal_color_7 = p.fg
	vim.g.terminal_color_8 = p.fg_dim
	vim.g.terminal_color_9 = p.pink
	vim.g.terminal_color_10 = p.green
	vim.g.terminal_color_11 = p.yellow
	vim.g.terminal_color_12 = p.orange
	vim.g.terminal_color_13 = p.purple
	vim.g.terminal_color_14 = p.cyan
	vim.g.terminal_color_15 = p.fg

	-- Plugins used in this config ------------------------------------------
	apply({
		BlinkCmpMenu = { link = "Pmenu" },
		BlinkCmpMenuBorder = { link = "PmenuBorder" },
		BlinkCmpMenuSelection = { link = "PmenuSel" },
		BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
		BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
		BlinkCmpLabel = { fg = p.fg },
		BlinkCmpLabelDeprecated = { fg = p.fg_dim, strikethrough = true },
		BlinkCmpLabelMatch = { link = "PmenuMatch" },
		BlinkCmpLabelDetail = { fg = p.fg_muted },
		BlinkCmpLabelDescription = { fg = p.fg_muted },
		BlinkCmpKind = { fg = p.fg_muted },
		BlinkCmpKindText = { fg = p.yellow },
		BlinkCmpKindMethod = { fg = p.green },
		BlinkCmpKindFunction = { fg = p.green },
		BlinkCmpKindConstructor = { fg = p.green },
		BlinkCmpKindField = { fg = p.orange },
		BlinkCmpKindVariable = { fg = p.cyan },
		BlinkCmpKindClass = { fg = p.cyan },
		BlinkCmpKindInterface = { fg = p.cyan },
		BlinkCmpKindModule = { fg = p.cyan },
		BlinkCmpKindProperty = { fg = p.fg },
		BlinkCmpKindUnit = { fg = p.purple },
		BlinkCmpKindValue = { fg = p.purple },
		BlinkCmpKindEnum = { fg = p.purple },
		BlinkCmpKindKeyword = { fg = p.pink },
		BlinkCmpKindSnippet = { fg = p.green },
		BlinkCmpKindColor = { fg = p.purple },
		BlinkCmpKindFile = { fg = p.fg_soft },
		BlinkCmpKindReference = { fg = p.purple },
		BlinkCmpKindFolder = { fg = p.fg_soft },
		BlinkCmpKindEnumMember = { fg = p.purple },
		BlinkCmpKindConstant = { fg = p.purple },
		BlinkCmpKindStruct = { fg = p.cyan },
		BlinkCmpKindEvent = { fg = p.orange },
		BlinkCmpKindOperator = { fg = p.pink },
		BlinkCmpKindTypeParameter = { fg = p.orange },
		BlinkCmpSource = { fg = p.fg_dim },
		BlinkCmpGhostText = { fg = p.fg_dim, italic = true },
		BlinkCmpDoc = { link = "NormalFloat" },
		BlinkCmpDocBorder = { link = "FloatBorder" },
		BlinkCmpDocSeparator = { fg = p.bg_border, bg = p.bg },
		BlinkCmpSignatureHelp = { link = "NormalFloat" },
		BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
		BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },

		TelescopeNormal = { link = "NormalFloat" },
		TelescopeBorder = { link = "FloatBorder" },
		TelescopeTitle = { link = "FloatTitle" },
		TelescopePromptNormal = { link = "NormalFloat" },
		TelescopePromptBorder = { link = "FloatBorder" },
		TelescopePromptTitle = { link = "FloatTitle" },
		TelescopePromptPrefix = { fg = p.cyan },
		TelescopePromptCounter = { fg = p.pink, bold = true },
		TelescopePreviewNormal = { link = "NormalFloat" },
		TelescopePreviewBorder = { link = "FloatBorder" },
		TelescopePreviewTitle = { link = "FloatTitle" },
		TelescopeResultsNormal = { link = "NormalFloat" },
		TelescopeResultsBorder = { link = "FloatBorder" },
		TelescopeResultsTitle = { link = "FloatTitle" },
		TelescopeSelection = { link = "PmenuSel" },
		TelescopeSelectionCaret = { fg = p.yellow, bg = p.bg_cursor, bold = true },
		TelescopeMatching = { fg = p.orange, bold = true },
		TelescopeMultiSelection = { fg = p.purple },
		TelescopeMultiIcon = { fg = p.green },

		GitSignsAdd = { fg = p.green },
		GitSignsChange = { fg = p.orange },
		GitSignsDelete = { fg = p.pink },
		GitSignsChangedelete = { fg = p.pink },
		GitSignsTopdelete = { fg = p.pink },
		GitSignsUntracked = { fg = p.cyan },
		GitSignsAddInline = { bg = p.add_word_bg },
		GitSignsChangeInline = { bg = p.change_word_bg },
		GitSignsDeleteInline = { bg = p.delete_word_bg },
		GitSignsCurrentLineBlame = { fg = p.fg_dark, italic = true },

		OilDir = { fg = p.cyan, bold = true },
		OilDirIcon = { fg = p.cyan },
		OilLink = { fg = p.purple },
		OilLinkTarget = { fg = p.fg_muted },
		OilCopy = { fg = p.yellow },
		OilCreate = { fg = p.green },
		OilDelete = { fg = p.pink },
		OilChange = { fg = p.orange },

		TroubleNormal = { link = "Normal" },
		TroubleNormalNC = { link = "NormalNC" },
		TroubleText = { fg = p.fg },
		TroubleCount = { fg = p.purple },
		TroubleFilename = { fg = p.cyan },
		TroubleSource = { fg = p.fg_muted },
		TroubleCode = { fg = p.fg_muted },

		NeogitDiffAdd = { fg = p.green, bg = p.add_bg },
		NeogitDiffDelete = { fg = p.pink, bg = p.delete_bg },
		NeogitDiffAddHighlight = { fg = p.green, bg = p.add_bg },
		NeogitDiffDeleteHighlight = { fg = p.pink, bg = p.delete_bg },
		NeogitDiffContext = { fg = p.fg_muted, bg = p.bg },
		NeogitDiffContextHighlight = { fg = p.fg, bg = p.bg_cursor },
		NeogitHunkHeader = { fg = p.cyan, bg = p.bg_dark, bold = true },
		NeogitHunkHeaderHighlight = { fg = p.cyan, bg = p.bg_element, bold = true },
		NeogitBranch = { fg = p.yellow, bold = true },
		NeogitRemote = { fg = p.green },
		NeogitFloatHeader = { link = "FloatTitle" },

		WhichKey = { fg = p.yellow },
		WhichKeyGroup = { fg = p.cyan },
		WhichKeyDesc = { fg = p.fg },
		WhichKeySeparator = { fg = p.fg_dim },
		WhichKeyBorder = { link = "FloatBorder" },
		WhichKeyFloat = { link = "NormalFloat" },
		WhichKeyNormal = { link = "NormalFloat" },

		LazyNormal = { link = "NormalFloat" },
		LazyButton = { fg = p.fg, bg = p.bg_element },
		LazyButtonActive = { fg = p.bg, bg = p.yellow, bold = true },
		LazyH1 = { fg = p.yellow, bold = true },
		LazyComment = { link = "Comment" },
		LazyUrl = { fg = p.green, underline = true },
		LazySpecial = { fg = p.orange },
		LazyProgressDone = { fg = p.green },
		LazyProgressTodo = { fg = p.fg_dark },

		MasonHeader = { fg = p.bg, bg = p.yellow, bold = true },
		MasonHighlight = { fg = p.cyan },
		MasonMuted = { fg = p.fg_muted },

		MiniIconsAzure = { fg = p.cyan },
		MiniIconsBlue = { fg = p.cyan },
		MiniIconsCyan = { fg = p.cyan },
		MiniIconsGreen = { fg = p.green },
		MiniIconsGrey = { fg = p.fg_muted },
		MiniIconsOrange = { fg = p.orange },
		MiniIconsPurple = { fg = p.purple },
		MiniIconsRed = { fg = p.pink },
		MiniIconsYellow = { fg = p.yellow },
	})
end

return M
