require('core.plugin_config.monokai_pro')
require('core.plugin_config.treesitter')
require('core.plugin_config.telescope')
require('core.plugin_config.lualine')
require('core.plugin_config.harpoon')
require('core.plugin_config.netrw')
require('core.plugin_config.lsp_config')
require('core.plugin_config.comment')
require('core.plugin_config.autopairs')
require('core.plugin_config.colorizer')
require('core.plugin_config.treesitter_context')
require('core.plugin_config.undotree')
require('core.plugin_config.gitsigns')
require('core.plugin_config.copilot')
require('core.plugin_config.cmp_config')

